### General Improvments * Adapted global exception handler to handle all the exceptions with the same format * Added exception handler at Security level (servlet)
### Improved CI/CD
* Minor workflow fixes
* Parameterized sensitive info in docker-compose.yml
* Parameterized sensitive info in app properties
* Improved deploy security and efficiency
* Added bash script to handle service deploy

diff --git a/.github/workflows/service_build_release.yml b/.github/workflows/service_build_release.yml
--- a/.github/workflows/service_build_release.yml
+++ b/.github/workflows/service_build_release.yml
@@ -1,6 +1,14 @@
 name: Build and Release Service
 
 on:
+  workflow_dispatch:
+    inputs:
+      logLevel:
+        description: 'Log level'
+        required: true
+        default: 'warning'
+      tags:
+        description: 'Forced build'
   push:
     branches:
       - main
@@ -47,6 +55,7 @@ jobs:
     permissions: write-all
     outputs:
       new-tag: ${{ steps.new_version.outputs.NEW_TAG }}
+      tag-message: ${{ steps.commit_messages.outputs.commit_messages }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -61,6 +70,9 @@ jobs:
             version=$(git describe --tags --abbrev=0 --match "v*" || echo "v0.0.0")
           fi
           echo "TAG=$version" >> $GITHUB_ENV
+          
+          real_version=$(git describe --tags --abbrev=0 --match "v*" || echo "v0.0.0")
+          echo "REAL_OLD_TAG=$real_version" >> $GITHUB_ENV
 
       - name: Increment version
         id: new_version
@@ -83,13 +95,7 @@ jobs:
           new_version="$major.$minor.$patch"
           echo "NEW_TAG=$new_version" >> $GITHUB_ENV
           echo "NEW_TAG=$new_version" >> $GITHUB_OUTPUT
-      
-
-      - name: Create and push new tag
-        uses: tvdias/github-tagger@v0.0.1
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          tag: ${{ env.NEW_TAG }}
+    
 
       - name: Update build.gradle
         run: |
@@ -105,7 +111,6 @@ jobs:
           else
             echo "docker-compose.yml not found, skipping update."
           fi
-          
           
 
       - name: Commit and push changes
@@ -145,7 +150,80 @@ jobs:
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           prerelease: false
-          automatic_release_tag: "${{  needs.prepare_release.outputs.new-tag }}"
+          automatic_release_tag: "latest"
           title: "Release ${{  needs.prepare_release.outputs.new-tag }}"
           files: |
             *.jar
+
+  deploy:
+    name: Deploy Service
+    permissions: write-all
+    environment: aws
+    needs: build
+    runs-on: ubuntu-latest
+    env:
+      SSH_USER: ${{ secrets.SSH_USER }}
+      SSH_HOST: ${{ secrets.SSH_HOST }}
+      SSH_PATH: ${{ secrets.SSH_PATH }}
+      SSH_KEY:  ${{ secrets.SSH_KEY }}
+      ENV_FILE: ${{ secrets.ENV_FILE }}
+      DEPLOY:   ${{ vars.DEPLOY }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: service-jar
+
+      - name: Deploy
+        run: |
+          if  [ "$DEPLOY" != 1  ]; then
+            echo "Skipping deployment due to missing requirements"
+            exit 0
+          fi
+          
+          if [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ] || [ -z "$SSH_PATH" ] || [ -z "$SSH_KEY" ]; then
+            echo "Missing required environment variables"
+            exit 1
+          fi
+
+          echo "Deploying service jar to server"
+          
+          artifact_name=$(ls *.jar)
+          
+          echo "$SSH_KEY" > key.pem
+          chmod 600 key.pem
+          
+          echo "$ENV_FILE" > .env
+          
+          if [ ! -f "docker-compose.yml" ]; then
+            echo "Missing docker-compose.yml"
+            exit 1
+          fi
+          
+          if [ ! -f "$artifact_name" ]; then
+            echo "Missing service jar"
+            exit 1
+          fi
+          
+          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "mkdir -p $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
+          
+          scp -o StrictHostKeyChecking=no -i key.pem *.jar $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/$artifact_name
+          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/docker-compose.yml
+          scp -o StrictHostKeyChecking=no -i key.pem .env $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/.env
+          scp -o StrictHostKeyChecking=no -i key.pem upservice.sh $SSH_USER@$SSH_HOST:$SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}/upservice.sh
+          
+          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST "cd $SSH_PATH${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/} ; sudo chmod +x upservice.sh ; ./upservice.sh"
+
+  clean:
+    runs-on: ubuntu-latest
+    needs: [ build, prepare_release, release, deploy ]
+    if: always()
+    name: Clean up
+    steps:
+      - name: Delete artifact
+        uses: geekyeggo/delete-artifact@v5
+        with:
+          name: service-jar
